#!/usr/bin/env python3
"""Generate the tool-neutral core of the spec-flow pipeline.

Single source of truth = memory/constitution.md + flow/*.md + templates/*.
Every tool adapter (Claude skills, Cursor commands, Antigravity workflows,
Copilot prompts) is a thin pointer to flow/*.md, generated by build_adapters.py.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

PHASES = ["specify", "plan", "tasks", "implement", "verify"]


def write(rel: str, text: str) -> None:
    p = ROOT / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text.lstrip("\n"), encoding="utf-8")
    print(f"  wrote {rel}")


# --------------------------------------------------------------------------
# memory/constitution.md  — the always-on principles every phase respects
# --------------------------------------------------------------------------
write("memory/constitution.md", r"""
# Project Constitution

> The non-negotiable principles every agent obeys in **every** phase of the
> pipeline. When a request conflicts with the constitution, the constitution
> wins — surface the conflict to the human instead of silently working around it.

## Article I — Spec before code
No production code is written before an **approved** `spec.md`. Ambiguity is
resolved with the human, not by guessing. Each spec states *what* and *why*,
never *how*.

## Article II — Plan before tasks
No task list exists before an **approved** `plan.md`. The plan owns all
*how* decisions: architecture, data flow, tech choices, and trade-offs.

## Article III — Test-first
Every behavioural task starts from a failing test (Red → Green → Refactor).
Tests are the executable form of the spec's acceptance criteria.

## Article IV — Small, reversible steps
One task = one focused, independently reviewable change with its own commit.
If a task cannot be expressed in a single coherent commit, it is too big — split it.

## Article V — Traceability
Every requirement traces to at least one test, and every test traces back to a
requirement ID. Code with no requirement is scope creep; a requirement with no
test is unverified.

## Article VI — Context isolation
Long-running work is decomposed so each task runs in a clean context. State that
must survive across tasks lives in files under `specs/<feature>/`, never only in
the agent's head.

## Article VII — Human gates
Three gates require explicit human approval before the pipeline advances:
`spec → plan`, `plan → tasks`, `tasks → implement`. An agent never approves its
own artifact.

## Article VIII — Honesty about limits
Agents report blockers, missing context, and uncertainty plainly. A wrong answer
delivered confidently is worse than a flagged unknown.

## Article IX — The spec is amended, never bypassed
When implementation reveals the spec is wrong or incomplete, work **stops**. You do
not silently edit code around the spec. You run the **amendment protocol**: change
the affected `REQ`, log it in the spec changelog, set the spec back to
`needs-approval`, get re-approval at the gate, then regenerate only the impacted
tasks. Code and spec move together or not at all. (See `flow/sync.md`.)

## Article X — Durable memory lives in `context.md`
Every feature keeps a `context.md` decision journal: constraints, assumptions,
rejected alternatives, and a dated decision log. It is updated **as work happens**,
not reconstructed afterward. Any agent starting a fresh session re-reads
`spec.md` + `plan.md` + `tasks.md` (status) + `context.md` before acting. This is
what prevents "why was it built this way?" amnesia two weeks later.

## Article XI — Traceability is machine-verified
Rastreability is not an honor system. Requirements are tagged in code and tests
(`REQ-xxx`), and `scripts/trace.py` builds the matrix from the *real* tree and
**fails CI** when an implemented requirement has no test, or code references a
requirement no spec declares. A spec only "counts" while the build proves it is in
sync with what ships.
""")


# --------------------------------------------------------------------------
# flow/*.md  — canonical phase procedures (the single source of truth)
# --------------------------------------------------------------------------
write("flow/specify.md", r"""
# Phase 1 — Specify

**Goal:** turn a raw idea into a rigorous, testable `spec.md`. Output *what* and
*why*, never *how*.

**Inputs:** the user's feature idea, plus `memory/constitution.md`.
**Output:** `specs/<NNN-feature-slug>/spec.md` (use `templates/spec.template.md`).
**Gate:** pause for explicit human approval before Phase 2.

## Procedure
1. Read `memory/constitution.md`. If the idea conflicts with any article, raise it now.
2. Pick the next feature number `NNN` (zero-padded) and a short slug. Create the
   folder `specs/<NNN-slug>/`.
3. Interview the human about anything ambiguous: actors, triggers, success
   criteria, edge cases, non-goals, constraints. Ask the **smallest** set of
   questions that removes real ambiguity — do not interrogate.
4. Write requirements in **EARS** syntax (Easy Approach to Requirements Syntax):
   - Ubiquitous: `The <system> shall <response>.`
   - Event-driven: `When <trigger>, the <system> shall <response>.`
   - State-driven: `While <state>, the <system> shall <response>.`
   - Unwanted: `If <condition>, then the <system> shall <response>.`
   - Optional: `Where <feature is included>, the <system> shall <response>.`
   Give every requirement a stable ID (`REQ-001`, `REQ-002`, …).
5. For each requirement add **acceptance criteria** phrased so they can become tests.
6. Fill the `## Non-goals` and `## Open questions` sections. Mark unresolved items
   with `[NEEDS CLARIFICATION: …]` rather than inventing an answer.
7. Save the file. Summarise the spec in 3–5 bullets and **stop**: ask the human to
   review and approve, or list the `[NEEDS CLARIFICATION]` items blocking approval.

## Amendment mode (`/specify --amend <feature>`)
Use this when a *later* phase discovers the spec is wrong or incomplete (Article IX).
Do **not** rewrite the whole spec:
1. Edit only the affected `REQ-xxx` (or add a new one with the next ID — never reuse).
2. Append a row to the spec's `## Changelog`: date, what changed, why, who triggered it.
3. Set `Status: needs-approval` and stop for re-approval at the gate.
4. After approval, hand off to `/tasks --refresh` so only the impacted tasks regenerate,
   then resume `/implement`. Record the amendment in the feature's `context.md`.

## Definition of done
- Every requirement is EARS-formatted, ID'd, and has acceptance criteria.
- No `[NEEDS CLARIFICATION]` markers remain (or they are explicitly accepted by the human).
- Non-goals are stated. The human has approved.
""")

write("flow/plan.md", r"""
# Phase 2 — Plan

**Goal:** turn an approved `spec.md` into a `plan.md` that owns every *how*
decision. No code yet.

**Inputs:** approved `specs/<feature>/spec.md`, `memory/constitution.md`.
**Output:** `specs/<feature>/plan.md` (use `templates/plan.template.md`).
**Gate:** pause for explicit human approval before Phase 3.

## Procedure
1. Confirm `spec.md` is approved and free of `[NEEDS CLARIFICATION]`. If not, go back.
2. Survey the existing codebase before proposing anything: language, framework,
   conventions, neighbouring modules, test setup. Reuse existing patterns over
   inventing new ones.
3. Choose an architecture that satisfies the spec with the least new surface area.
   Document the **data flow**, the **components** touched/created, and the
   **interfaces/contracts** between them.
4. Record every significant decision as a short ADR-style entry: *decision*,
   *alternatives considered*, *why this one*. Tie each back to the REQ IDs it serves.
5. Call out risks, migrations, rollout/rollback, and observability needs.
6. Map each `REQ-xxx` to the component(s) that will satisfy it, so nothing is dropped.
7. Save the file. Summarise the approach and **stop** for human approval.

## Definition of done
- Every `REQ-xxx` from the spec maps to at least one component in the plan.
- Tech choices are justified against alternatives and the constitution.
- Risks, rollback, and test strategy are explicit. The human has approved.
""")

write("flow/tasks.md", r"""
# Phase 3 — Tasks

**Goal:** decompose an approved `plan.md` into an ordered, dependency-aware task
list where each task is small, testable, and independently committable.

**Inputs:** approved `specs/<feature>/plan.md`, the spec, the constitution.
**Output:** `specs/<feature>/tasks.md` (use `templates/tasks.template.md`).
**Gate:** pause for explicit human approval before Phase 4.

## Procedure
1. Confirm `plan.md` is approved.
2. Break the plan into tasks. Each task must:
   - have a stable ID (`T-001`, `T-002`, …);
   - reference the `REQ-xxx` it advances and the plan component it touches;
   - be doable in a single focused commit (Article IV);
   - name the test(s) that prove it (Article III).
3. Declare **dependencies** between tasks (`depends_on: [T-001]`). Order so that
   independent tasks can run in parallel and blocked tasks come after their blockers.
4. Front-load a task that writes the failing tests for the slice, when that makes
   the TDD loop cleaner.
5. Add a final task that runs Phase 5 (verify) for the feature.
6. Save the file. Summarise the task graph (count, parallelizable set, critical
   path) and **stop** for human approval.

## Refresh mode (`/tasks --refresh <feature>`)
Triggered after a spec amendment (Article IX). Do **not** rebuild the whole list:
1. Diff the amended spec against the current tasks.
2. Mark tasks tied to a changed `REQ` as `stale`; add new tasks for new requirements.
3. Leave untouched tasks (and their commits) exactly as they are.
4. Summarise what changed and stop for approval before re-running `/implement`.

## Definition of done
- Every task is ID'd, traces to a REQ and a plan component, and names its tests.
- Dependencies form a valid DAG (no cycles). The human has approved.
""")

write("flow/implement.md", r"""
# Phase 4 — Implement

**Goal:** execute the approved task list. You act as the **tech lead /
orchestrator**; each task is delegated to an isolated worker so context stays clean.

**Inputs:** approved `specs/<feature>/tasks.md`, the plan, the spec, the constitution.
**Output:** working, tested code; one commit per task.

## Before you start
1. **Gate check.** Confirm `spec.md` and `plan.md` both read `Status: approved`
   (or run `python scripts/check_gate.py specs/<feature>`). If not, stop — you are
   not cleared to implement.
2. **Resume context (Article X).** Re-read `spec.md`, `plan.md`, `tasks.md` (note
   each task's status), and `context.md` before touching code. Find the first task
   that is `todo` with all `depends_on` satisfied; that is where you start.

## Orchestration loop
For each task in dependency order (parallelize independent tasks where the tool allows):

1. **Dispatch in isolation.** Hand the single task to a worker with a *clean*
   context (in Claude Code: the `developer` subagent / a forked context; in
   Antigravity: a worker agent; elsewhere: a fresh sub-task). Give it only what it
   needs: the task, its REQs, the relevant plan section, and the files in scope.
2. **TDD.** The worker writes the failing test first, then the minimal code to pass,
   then refactors. It does **not** touch files outside the task's declared scope.
   **Tag traceability:** put the `REQ-xxx` ID in a comment beside the code that
   satisfies it and in the test (name or comment), so `scripts/trace.py` can see it.
3. **Verify locally.** Run the task's tests plus lint/typecheck. If red, fix within
   the task; if blocked, stop and report — do not expand scope.
4. **Commit.** One conventional commit referencing the task and REQ
   (e.g. `feat(T-003): add rate limiter [REQ-007]`). Record the commit SHA next to
   the task in `tasks.md` and flip its status to `done`. Then continue.
5. **Log blockers.** Anything discovered but out of scope is recorded as a new
   task in `tasks.md`, not fixed inline.

## When reality contradicts the spec (the reverse path — Article IX)
If implementation reveals the spec is wrong or incomplete, **do not patch around it**:
1. Stop the current task and write what you learned into `context.md`.
2. Run `/specify --amend <feature>` to fix the affected `REQ`, then `/tasks --refresh`.
3. Re-approve at the gate, then resume here. The spec and code move together.
Use `/sync` at any time to detect drift between what shipped and what the spec says.

## Rules
- Never start a task whose `depends_on` set is unmet.
- Never silently edit an approved spec/plan from here — use the amendment protocol above.
- Keep `tasks.md` status current (`todo` / `doing` / `done` / `blocked` / `stale`).
- Keep `context.md` current: log every non-obvious decision and constraint as you go.

## Definition of done
- Every task is `done` with a passing test and its own commit, or explicitly `blocked`
  with a reason. Proceed to Phase 5.
""")

write("flow/verify.md", r"""
# Phase 5 — Verify

**Goal:** prove the implementation satisfies the spec, and surface any gap.

**Inputs:** the spec, plan, tasks, and the implemented code + tests.
**Output:** a verification report (and, if gaps exist, new tasks in `tasks.md`).

## Procedure
1. Run `python scripts/trace.py` to build the traceability matrix from the real
   tree, then cross-check it: for every `REQ-xxx`, the test(s) that cover it and the
   task(s)/commit(s) that implemented it.
2. Flag any requirement with **no** covering test (Article V violation) and any
   `REQ` marker that maps to **no** requirement (scope creep). Run `/sync` if drift
   is found.
3. Run the full test suite, lint, and typecheck. Record results.
4. Re-read each acceptance criterion in the spec and confirm a test asserts it.
5. Check the constitution: small commits? human gates respected? context isolation
   honoured?
6. Write the report: ✅ covered, ⚠️ partial, ❌ missing. For every ❌/⚠️, create a
   follow-up task rather than hand-waving.
7. **Stop** and present the report. Do not declare the feature done while any
   `REQ` is uncovered.

## Definition of done
- Traceability matrix is complete; no uncovered REQ remains unaddressed.
- Full suite green. Report delivered to the human.
""")


# --------------------------------------------------------------------------
# templates/*  — the artifact shapes each phase fills in
# --------------------------------------------------------------------------
write("templates/spec.template.md", r"""
# Spec: <feature name>

- **Feature ID:** <NNN-slug>
- **Status:** draft | needs-approval | approved
- **Author:** <name>
- **Date:** <YYYY-MM-DD>

## Summary
<2–3 sentences: what this feature is and the user value.>

## Actors
<who/what interacts with this feature.>

## Requirements (EARS)
| ID | Type | Requirement | Acceptance criteria |
|----|------|-------------|---------------------|
| REQ-001 | event-driven | When <trigger>, the system shall <response>. | <observable, testable outcome> |
| REQ-002 | unwanted | If <condition>, then the system shall <response>. | <observable, testable outcome> |

## Non-goals
- <explicitly out of scope>

## Open questions
- [NEEDS CLARIFICATION: <question>]

## Changelog
> Appended by `/specify --amend` whenever an approved requirement changes (Article IX).

| Date | Change | Why | Trigger |
|------|--------|-----|---------|
| <YYYY-MM-DD> | initial spec | — | specify |
""")

write("templates/plan.template.md", r"""
# Plan: <feature name>  (<NNN-slug>)

- **Status:** draft | approved
- **Spec:** ./spec.md

## Approach
<the chosen architecture in a paragraph.>

## Components
| Component | New/changed | Responsibility | Serves REQs |
|-----------|-------------|----------------|-------------|
| <module>  | new         | <what it does> | REQ-001, REQ-003 |

## Data flow
<describe or diagram the flow across components.>

## Contracts / interfaces
<key signatures, schemas, or API shapes.>

## Decisions (ADR-style)
### D1 — <decision>
- **Alternatives:** <a>, <b>
- **Chosen because:** <reason, tied to REQ/constitution>

## Risks & rollback
- <risk> → <mitigation / rollback plan>

## Test strategy
<unit / integration / e2e split; how acceptance criteria become tests.>

## Requirement coverage
| REQ | Covered by component(s) |
|-----|-------------------------|
| REQ-001 | <component> |
""")

write("templates/tasks.template.md", r"""
# Tasks: <feature name>  (<NNN-slug>)

- **Status:** draft | approved
- **Plan:** ./plan.md

> Status legend: todo · doing · done · blocked

| ID | Task | Serves | Component | depends_on | Tests | Status |
|----|------|--------|-----------|------------|-------|--------|
| T-001 | <write failing tests for slice X> | REQ-001 | <module> | — | <test file> | todo |
| T-002 | <implement X> | REQ-001 | <module> | T-001 | <test file> | todo |
| T-003 | <verify feature> | all | — | T-002 | full suite | todo |

## Notes / blockers
- <discovered-but-out-of-scope items become new T-xxx rows above>
""")


# --------------------------------------------------------------------------
# Worked example feature
# --------------------------------------------------------------------------
write("specs/001-api-rate-limit/spec.md", r"""
# Spec: Per-client API rate limiting

- **Feature ID:** 001-api-rate-limit
- **Status:** approved
- **Author:** Juliano Souza
- **Date:** 2026-06-08

## Summary
Protect the public API from abuse by limiting how many requests a single client
key may make per minute, returning a clear, standards-compliant response when the
limit is exceeded.

## Actors
- API client (identified by API key)
- API gateway / middleware

## Requirements (EARS)
| ID | Type | Requirement | Acceptance criteria |
|----|------|-------------|---------------------|
| REQ-001 | event-driven | When a client sends a request, the system shall count it against that client's rolling 60-second window. | A counter increments per key; window slides correctly across the minute boundary. |
| REQ-002 | unwanted | If a client exceeds 100 requests in the window, then the system shall reject further requests with HTTP 429. | The 101st request in a window returns 429. |
| REQ-003 | ubiquitous | The system shall include `Retry-After` and `X-RateLimit-Remaining` headers on every API response. | Both headers present with correct values on 200 and 429. |
| REQ-004 | state-driven | While a client is below its limit, the system shall pass the request through unchanged. | Requests 1–100 behave identically to the unlimited path. |

## Non-goals
- Per-endpoint or tiered limits (future feature).
- Distributed limiting across regions (single-node window is acceptable for v1).

## Open questions
- (resolved) Limit is fixed at 100/min for v1.

## Changelog
| Date | Change | Why | Trigger |
|------|--------|-----|---------|
| 2026-06-08 | initial spec | — | specify |
""")

write("specs/001-api-rate-limit/plan.md", r"""
# Plan: Per-client API rate limiting  (001-api-rate-limit)

- **Status:** approved
- **Spec:** ./spec.md

## Approach
A middleware sits in front of the route handlers. It keys a sliding-window
counter by API key in an in-process store, decides allow/deny, and decorates the
response with rate-limit headers.

## Components
| Component | New/changed | Responsibility | Serves REQs |
|-----------|-------------|----------------|-------------|
| `RateLimiter` | new | sliding-window counting + allow/deny decision | REQ-001, REQ-002, REQ-004 |
| `rate_limit_middleware` | new | wire limiter into the request path, set headers | REQ-002, REQ-003 |
| store (in-memory) | new | per-key timestamps with TTL eviction | REQ-001 |

## Data flow
request → middleware → RateLimiter.check(key) → {allow → handler, deny → 429} →
middleware sets `Retry-After` / `X-RateLimit-Remaining` → response.

## Contracts / interfaces
- `RateLimiter.check(key: str, now: float) -> Decision(allowed: bool, remaining: int, retry_after: int)`

## Decisions (ADR-style)
### D1 — Sliding window over fixed window
- **Alternatives:** fixed window, token bucket
- **Chosen because:** avoids burst-at-boundary of fixed window; simpler than token
  bucket for a fixed per-minute cap (REQ-002).

## Risks & rollback
- In-memory store lost on restart → acceptable for v1 (single node, non-goal covers it).
- Rollback: feature-flag the middleware; disabling it restores the unlimited path.

## Test strategy
Unit tests for `RateLimiter` (window math, boundary), integration tests through the
middleware for 429 + headers.

## Requirement coverage
| REQ | Covered by component(s) |
|-----|-------------------------|
| REQ-001 | RateLimiter, store |
| REQ-002 | RateLimiter, middleware |
| REQ-003 | middleware |
| REQ-004 | RateLimiter |
""")

write("specs/001-api-rate-limit/tasks.md", r"""
# Tasks: Per-client API rate limiting  (001-api-rate-limit)

- **Status:** approved
- **Plan:** ./plan.md

> Status legend: todo · doing · done · blocked · stale

| ID | Task | Serves | Component | depends_on | Tests | Status | Commit |
|----|------|--------|-----------|------------|-------|--------|--------|
| T-001 | Write failing unit tests for sliding-window math incl. boundary | REQ-001, REQ-004 | RateLimiter | — | test_rate_limiter.py | todo | — |
| T-002 | Implement RateLimiter + in-memory store to pass T-001 | REQ-001, REQ-004 | RateLimiter, store | T-001 | test_rate_limiter.py | todo | — |
| T-003 | Write failing integration tests for 429 + headers | REQ-002, REQ-003 | middleware | T-002 | test_middleware.py | todo | — |
| T-004 | Implement rate_limit_middleware to pass T-003 | REQ-002, REQ-003 | middleware | T-003 | test_middleware.py | todo | — |
| T-005 | Verify: traceability matrix + full suite green | all | — | T-004 | full suite | todo | — |

## Notes / blockers
- none yet
""")

# --------------------------------------------------------------------------
# flow/sync.md  — the reverse path: detect & reconcile drift
# --------------------------------------------------------------------------
write("flow/sync.md", r"""
# Phase R — Sync (the reverse path)

**Goal:** detect and reconcile **drift** between what the spec says and what the
code actually does. This is the answer to "a spec only earns its keep while it stays
synced with what ships." Run it any time, and always before declaring a feature done.

**Inputs:** the spec/plan/tasks, the implemented code + tests, git history.
**Output:** a drift report; for each drift, a concrete reconciliation action.

## Three states
- **In sync** — every `REQ` has matching code + tests; no stray `REQ` markers. ✅
- **Spec ahead** — a `REQ` exists but code/tests don't implement it yet → it is just
  unstarted work; make sure a task covers it.
- **Code ahead** — code implements behaviour the spec doesn't describe, or references a
  `REQ` no spec declares → this is **drift**. Either the spec must be amended to
  capture the new intent, or the code is scope creep to remove.

## Procedure
1. Run `python scripts/trace.py` to build the matrix from the real tree (it lists
   uncovered REQs, untested REQs, and unknown `REQ` markers).
2. Compare git history against `tasks.md`: any commit touching feature code whose task
   is not `done`, or any `done` task with no commit, is drift.
3. Classify every gap into one of the three states above.
4. For each **code-ahead** drift, decide *with the human*:
   - intent was real → `/specify --amend` to capture it as a REQ, then `/tasks --refresh`;
   - it was scope creep → open a task to remove or gate it.
5. For each **spec-ahead** gap, ensure a task exists (or create one).
6. Update `context.md` with what drifted and how it was reconciled.
7. Present the report and **stop**. Do not auto-amend the spec without approval.

## Definition of done
- `scripts/trace.py` exits clean (no uncovered/unknown REQs for implemented work).
- Every drift is either reconciled or captured as an approved task. `context.md` updated.
""")

# --------------------------------------------------------------------------
# templates/context.template.md  — the per-feature decision journal
# --------------------------------------------------------------------------
write("templates/context.template.md", r"""
# Context journal: <feature name>  (<NNN-slug>)

> Durable memory for this feature (Constitution, Article X). Update it **as you
> work**, not afterward. Any agent or teammate starting fresh reads this first.

## Constraints
- <hard limits: deadlines, compatibility, perf budgets, things you must not break>

## Assumptions
- <what we are taking as given, and what would change if it turns out false>

## Decisions log
| Date | Decision | Why | Trigger |
|------|----------|-----|---------|
| YYYY-MM-DD | <what was decided> | <reasoning> | spec / plan / implement / sync |

## Rejected alternatives
- <option> — rejected because <reason> (so nobody re-litigates it in 2 weeks)

## Open questions
- <unknowns still in the air>

## Session resume
- **Last commit:** <sha>
- **Next task:** <T-xxx>
- **Watch out:** <gotchas the next session should know>
""")

write("specs/001-api-rate-limit/context.md", r"""
# Context journal: Per-client API rate limiting  (001-api-rate-limit)

> Durable memory for this feature (Constitution, Article X). Update it as you work.

## Constraints
- v1 runs on a single node; no shared store across regions (see spec Non-goals).
- Must not add latency to the happy path beyond a single in-memory lookup.

## Assumptions
- 100 req/min is the right default for v1 (confirmed with product; revisit at GA).
- Clients are uniquely identified by API key; anonymous traffic is out of scope.

## Decisions log
| Date | Decision | Why | Trigger |
|------|----------|-----|---------|
| 2026-06-08 | Sliding window over fixed window | Avoids burst-at-boundary; simpler than token bucket for a fixed cap | plan |
| 2026-06-08 | In-memory store, no persistence | Single-node v1; restart-loss is acceptable per Non-goals | plan |

## Rejected alternatives
- Token bucket — rejected: more moving parts than needed for a fixed per-minute cap.
- Redis-backed counter — rejected for v1: pulls in infra a single node doesn't need yet.

## Open questions
- Should limits become per-tier later? Tracked as a future feature, not this one.

## Session resume
- **Last commit:** (not started)
- **Next task:** T-001
- **Watch out:** write the window-boundary test first — it's the easy thing to get wrong.
""")

print("core: done")
